package Formularios;

import Clases.Preguntas;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Samuel David Ortiz
 */
public class FrmArbol extends javax.swing.JFrame {

    /**
     * Creates new form FrmArbol
     */
    Preguntas pregunta = new Preguntas();
    ArrayList<JButton> btnPreguntas;
    JPanel mainPanel;

    public FrmArbol() {
        initComponents();
        
        GridLayout grid = new GridLayout(16, 16);
        grid.setHgap(2);
        grid.setVgap(2);
        mainPanel = new JPanel(grid);
        
        btnPreguntas = new ArrayList<JButton>();
        
        for (int i = 0; i < 17; i++) {
            JButton c = new JButton();
            btnPreguntas.add(c);
            mainPanel.add(c);
        }

        //btn15.addActionListener(new MisPreguntas());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(9, 2, 10, 10));

        jButton1.setText("Pregunta 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Pregunta 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("Pregunta 3");
        jPanel1.add(jButton3);

        jButton4.setText("Pregunta 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("Pregunta 5");
        jPanel1.add(jButton5);

        jButton6.setText("Pregunta 6");
        jPanel1.add(jButton6);

        jButton7.setText("Pregunta 7");
        jPanel1.add(jButton7);

        jButton8.setText("Pregunta 8");
        jPanel1.add(jButton8);

        jButton9.setText("Pregunta 9");
        jPanel1.add(jButton9);

        jButton10.setText("Pregunta 10");
        jPanel1.add(jButton10);

        jButton11.setText("Pregunta 11");
        jPanel1.add(jButton11);

        jButton12.setText("Pregunta 12");
        jPanel1.add(jButton12);

        jButton13.setText("Pregunta 13");
        jPanel1.add(jButton13);

        jButton14.setText("Pregunta 14");
        jPanel1.add(jButton14);

        btn15.setText("Pregunta 15");
        jPanel1.add(btn15);

        jButton16.setText("Pregunta 16");
        jPanel1.add(jButton16);

        jButton17.setText("Pregunta 17");
        jPanel1.add(jButton17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        pregunta.mensaje("¿Qué nodo es la raíz?\n\nEl nodo raiz es el nodo A", 1);

        //JOptionPane.showMessageDialog(null, "¿Qué nodo es la raíz?\n\nEl nodo raiz es el nodo A");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pregunta.mensaje("¿Cuántos caminos diferentes de longitud tres hay?\n\nSolamente hay un camino con longitud 3", 2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    public class MisPreguntas implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent a) {

            File abre = new File("./preguntas.txt");
            int xx = 0;

            try {
                if (abre != null) {
                    Scanner scan = new Scanner(abre);
                    ArrayList<String> data = new ArrayList<String>();

                    while (scan.hasNextLine()) {
                        //btnPreguntas.add(xx);
                        String c;
                        c = scan.nextLine();
                        int l = c.length();
                        int z[] = new int[l];
                        String x[] = new String[l];

                        x = c.split(",");

                        data.add(x[0]);
                        System.out.println(x[0]);

                        xx++;

                    }
                }

            } catch (Exception e) {
            }
            
            for (int i = 0; i < 17; i++) {
                
                
            }

            pregunta.mensaje("¿Cuántos caminos diferentes de longitud tres hay?\n\nSolamente hay un camino con longitud 3", 2);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmArbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn15;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
